name: search_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  search_app_bar:
    path: ../
  rxdart:
    git:
      url: https://github.com/ReactiveX/rxdart
      ref: master
  diacritic: ^0.1.1
  cupertino_icons: ^0.1.2
  dio: ^3.0.10
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
